name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://madhav-lakhotia:$HF_TOKEN@huggingface.co/spaces/madhav-lakhotia/MindMate
          # 🔥 Custom Git Push Options to bypass LFS/Xet strict hooks for asset images
          git push --force -o issue=true hf main